apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_OPTIONS_EDITORTHEME
              value: ambiance
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-srv
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: super
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: super
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongo-express-srv
spec:
  selector:
    app: mongo-express
  type: NodePort
  ports:
    - name: mongo-express
      protocol: TCP
      port: 8081
      targetPort: 8081
